name: Build and upload local flatpak

on:
  #schedule:
  #  - cron: '23 3 * * *'
  workflow_dispatch:
    inputs:
      version:
        description: 'Branch or Tag to build'
        default: 'GTK3V2MAIN'
        required: true
        type: string
      sf_user:
        description: 'Sourceforge username (expects SF_SSH_KEY secret to contain private key)'
        default: 'str0belight'
        required: true
        type: string
      upload_dir:
        description: 'Relative directory path to upload to'
        default: 'Development/Flatpak/TestBuilds'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update
        run: |
          sudo apt-get update -q

      - name: Install dependencies
        run: |
          sudo apt-get install -yqq \
            flatpak-builder \
            libgtk-3-dev \
            libcmocka-dev \
            libzip-dev \
            libmxml-dev \
            librsvg2-bin \
            gettext \
            file

      - name: Start ssh-agent and add key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SF_SSH_KEY: ${{ secrets.SF_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "$SF_SSH_KEY" > ~/.ssh/sourceforge_key
          chmod 600 ~/.ssh/sourceforge_key
          ssh-keyscan hg.code.sf.net >> ~/.ssh/known_hosts
          eval "$(ssh-agent -a $SSH_AUTH_SOCK)"
          ssh-add ~/.ssh/sourceforge_key

      - name: Get XtrackCad source and update to desired version
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          hg clone ssh://${{ inputs.sf_user }}@hg.code.sf.net/p/xtrkcad-fork/xtrkcad repo
          cd repo
          hg update "${{ inputs.version }}"

      - name: Update description
        run: |
          cd repo
          CHANGESET=$(hg log -r . -T '{rev}')
          sed -i "s/^#define DESCRIPTION .*/#define DESCRIPTION N_(\"Test XtrackCad build from ${{ inputs.version }} (changeset $CHANGESET).\")/" app/bin/smalldlg.c

      - name: Configure build
        run: |
          cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Debug repo

      - name: Build flatpak (no output for a while)
        id: fp_out
        run: |
          cd build
          ninja flatpak
          #artifact=$(ls xtrkcad-*.flatpak)
          #echo "artifact=${artifact}" >> $GITHUB_OUTPUT

      - name: Upload artifact to github
        uses: actions/upload-artifact@v7
        with:
          name: flatpak
          path: build/xtrkcad-*.flatpak
          retention-days: 5
          overwrite: true
          archive: false

      - name: Upload to sourceforge
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp build/xtrkcad-*.flatpak ${{ inputs.sf_user }}@frs.sourceforge.net:/home/pfs/project/xtrkcad-fork/${{ inputs.upload_dir }}/
